### ISSUE TITLE
set Bindings in Map in Script

### ISSUE THREAD

**Issue by weberjn** [eobermuhlner/java-scriptengine#12]
Currently java-scriptengine sets each key/value of the Bindings to attributes of the class. For more entries in the bindings map this is not practical. ([openHAB sets some 70 bindings ..](https://www.openhab.org/docs/configuration/jsr223.html))
Could you please push the bindings to a Map in the script, this possibly controllable by a strategie? 

s.th. along

    m = compiledClass.getMethod("setBindings", Map.class);
    m.invoke(compiledInstance, mergedBindings);

Thanks, Jürgen

**Comment by eobermuhlner** [comment]
Hi Jürgen

I am not sure whether I understand completely.

If you want to transfer many values between the outer application and the
script class you can use a field of type `Map`.
This should fulfill your requirements.

For example:

private static void runCompileDifferentTypesExample() {
    try {
        ScriptEngineManager manager = new ScriptEngineManager();
        ScriptEngine engine = manager.getEngineByName("java");
        Compilable compiler = (Compilable) engine;

        CompiledScript compiledScript = compiler.compile("" +
                "import java.util.*;" +
                "public class Script implements Runnable {" +
                "   public int intValue = 1;" +
                "   public Map<String, String> mapStringStringValue =
new HashMap<>();" +
                "   public void run() {" +
                "       intValue++;" +
                "       mapStringStringValue.put(\"Hello\", \"world\");" +
                "   } " +
                "}");

        Bindings bindings = engine.createBindings();

        bindings.put("intValue", 90);
        Map<String, String> outerMapStringStringValue = new HashMap<>();
        outerMapStringStringValue.put("injected", "before running script");
        bindings.put("mapStringStringValue", outerMapStringStringValue);

        Object result = compiledScript.eval(bindings);

        System.out.println("Result: " + result);
        System.out.println("Variable intValue: " + bindings.get("intValue"));
        System.out.println("Variable mapStringStringValue: " +
bindings.get("mapStringStringValue"));
        System.out.println("LocalVariable outerMapStringStringValue: "
+ outerMapStringStringValue);
    } catch (ScriptException e) {
        e.printStackTrace();
    }
}

This will print the following output:

Result: null
Variable intValue: 91
Variable mapStringStringValue: {Hello=world, injected=before running script}
LocalVariable outerMapStringStringValue: {Hello=world, injected=before
running script}

What do you think?

Best regards,
Eric Obermühlner

**Comment by weberjn** [comment]
Hi Eric,

thanks for the sample.
the calling system is openHAB, the way the script is called is given, and they set each binding entry on it's own.

Anyway, I have made more changes for https://github.com/weberjn/org.openhab.automation.javarules
Made Memory JavaFileManager forwarding as the Oracle doc suggests 

and added location CLASS_PATH to the list method (https://github.com/weberjn/org.openhab.automation.javarules/blob/master/src/main/java/ch/obermuhlner/scriptengine/java/MemoryForwardingJavaFileManager.java) so a Java script can use classes from the classpath.

Would you care to have a look at the changes to include them into your code?

Greetings,
Jürgen

**Comment by eobermuhlner** [comment]
Hi Jürgen

Adding the location CLASS_PATH sounds like a good thing.
Your code uses a class org.
openhab.automation.javarules.internal.PackageResourceLister from your
project so I cannot use it directly like this.

If you want, you can do a pull request for
https://github.com/eobermuhlner/java-scriptengine and I will happily review
and merge it.

Best regards,
Eric
